---
- name: Restart listener
  shell: |
    ORACLE_HOME={{ oracle_home }} \
    runuser -u {{ oracle_user }} -- \
      {{ oracle_home }}/bin/lsnrctl reload {{ listener_name }}
  args:
    executable: /bin/bash
  listen: "restart listener"
