packer {
  required_plugins {
    proxmox = {
      version = ">= 1.1.2"
      source  = "github.com/hashicorp/proxmox"
    }
  }
}

variable "proxmox_api_url" {
  type = string
}

variable "proxmox_api_token_id" {
  type = string
}

variable "proxmox_api_token_secret" {
  type      = string
  sensitive = true
}

source "proxmox-iso" "oraclelinux" {
  # Connection Settings
  proxmox_url              = var.proxmox_api_url
  username                 = var.proxmox_api_token_id
  token                    = var.proxmox_api_token_secret
  insecure_skip_tls_verify = true

  # VM Identity
  node                 = "praslab"
  vm_id                = 9991
  vm_name              = "oraclelinux-9-template"
  template_name        = "oraclelinux-9-gold-template"
  template_description = "Oracle Linux 9 Template generated by Packer"

  # Hardware
  cores    = 2
  memory   = 2048
  os       = "l26"
  cpu_type = "host"

  # Use the more compatible VirtIO SCSI Single controller
  scsi_controller = "virtio-scsi-single"

  # Disk and Network
  disks {
    disk_size    = "20G"
    storage_pool = "local-lvm"
    type         = "scsi"
    format       = "raw"
  }

  network_adapters {
    model  = "virtio"
    bridge = "vmbr0"
  }

  # Cloud-Init support
  cloud_init              = true
  cloud_init_storage_pool = "local-lvm"

  # Boot ISO block
  boot_iso {
    type     = "ide"
    iso_file = "local:iso/OracleLinux-R9-U7-x86_64-dvd.iso"
    unmount  = true
    index    = 2
  }

  # SSH Credentials (must match ks.cfg)
  ssh_username = "packer"
  ssh_password = "packer"
  ssh_timeout  = "20m"

  # Boot Command for Oracle Linux 9 (same Anaconda installer as AlmaLinux/RHEL)
  boot_command = [
    "<tab> ip=dhcp inst.ks=http://{{ .HTTPIP }}:{{ .HTTPPort }}/ks.cfg inst.repo=cdrom<enter>"
  ]
  http_directory = "http"
}

build {
  sources = ["source.proxmox-iso.oraclelinux"]

  # Runs inside the VM via SSH after OS installation
  provisioner "shell" {
    inline = [
      "echo 'Installing Guest Agent and Cloud-Init...'",
      "sudo dnf install -y qemu-guest-agent cloud-init cloud-utils-growpart",
      "sudo systemctl enable qemu-guest-agent cloud-init",

      "echo 'Cleaning up image to reduce size...'",
      "sudo dnf clean all",
      "sudo rm -rf /var/cache/dnf",

      "echo 'Resetting machine-id for unique clones...'",
      "sudo truncate -s 0 /etc/machine-id",
      "sudo rm -f /etc/ssh/ssh_host_*"
    ]
  }
}
